# Generated by Django 2.1.3 on 2018-12-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20181207_1127'),
        ('testapp', '0005_auto_20181207_1342'),
    ]

    operations = [
    ]
