# Generated by Django 2.1.3 on 2018-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_merge_20181225_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
