# Generated by Django 2.1.3 on 2018-12-03 11:04

import denormalized.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_member_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=denormalized.models.DenormalizedForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Group'),
        ),
    ]
