# Generated by Django 2.1.3 on 2018-12-07 11:27

import django.db.models.deletion
from django.db import migrations, models

import denormalized.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20181203_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_sum', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=denormalized.models.DenormalizedForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Team'),
        ),
    ]
